### ISSUE TITLE
`brew doctor` is complaining

### ISSUE THREAD

**Issue by newbery** [beeftornado/homebrew-rmtree#15]
Not seeing any consequence to this yet but wondering if I should be concerned that `brew doctor` complains...
```
Found command `brew-rmtree` in following places:
  /usr/local/bin/brew-rmtree.rb
  /usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb
```

**Comment by beeftornado** [comment]
This could be due to #13 which we had to fix by moving the script. This may have left you with two scripts. This user reportedly just removed it and reinstalled it. https://github.com/beeftornado/homebrew-rmtree/issues/13#issuecomment-272613425
