### ISSUE TITLE
Feature Request: Add option to ignore some dependencies from removal

### ISSUE THREAD

**Issue by pablocrivella** [beeftornado/homebrew-rmtree#2]
Maybe something like...

```brew rmtree meld --ignore python```

**Comment by erayalakese** [comment]
Looking for same feature. 

Today I decided to remove winetricks so executed this command :

     $ brew rmtree winetricks

But this removed *wine* package, too . Because it's one of the dependencies of *winetricks* . And I didn't want to remove *wine* package .

**Comment by beeftornado** [comment]
Ok, I will add this feature shortly. Thanks for the feedback.
