### ISSUE TITLE
Error running brew rmtree

### ISSUE THREAD

**Issue by echosa** [beeftornado/homebrew-rmtree#30]
I'm getting this error when trying to `$ brew rmtree mpg123`:

```
$ brew rmtree mpg123
Warning: Calling <<-EOS.undent is deprecated!
Use <<~EOS instead.
/usr/local/bin/brew-rmtree.rb:45:in `<module:BrewRmtree>'

Error: undefined method `default_formula' for #<MacOSRequirement: "macos" [:mountain_lion]>
/usr/local/bin/brew-rmtree.rb:146:in `block (3 levels) in uses'
/usr/local/bin/brew-rmtree.rb:146:in `any?'
/usr/local/bin/brew-rmtree.rb:146:in `block (2 levels) in uses'
/usr/local/bin/brew-rmtree.rb:127:in `each'
/usr/local/bin/brew-rmtree.rb:127:in `all?'
/usr/local/bin/brew-rmtree.rb:127:in `block in uses'
/usr/local/bin/brew-rmtree.rb:126:in `select'
/usr/local/bin/brew-rmtree.rb:126:in `uses'
/usr/local/bin/brew-rmtree.rb:321:in `rmtree'
/usr/local/bin/brew-rmtree.rb:391:in `block in main'
/usr/local/bin/brew-rmtree.rb:391:in `each'
/usr/local/bin/brew-rmtree.rb:391:in `main'
/usr/local/bin/brew-rmtree.rb:395:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:20:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:106:in `<main>'
```

**Comment by beeftornado** [comment]
Are you using the most recent version? I ask because the line numbers in your stack trace don't match up to the source code.

**Comment by mikchmie-ifm** [comment]
I'm experiencing the same problem as author of this issue. I checked the version and that's what I've got:

```
$ brew info brew-rmtree
brew-rmtree: stable 2.0, HEAD
https://github.com/beeftornado/homebrew-rmtree
/usr/local/Cellar/brew-rmtree/2.0 (5 files, 20.4KB) *
  Built from source on 2016-11-23 at 16:37:00
From: /usr/local/opt/brew-rmtree/.brew/brew-rmtree.rb
==> Options
--HEAD
	Install HEAD version
```
Year 2016 didn't really look up to date. I perform brew update  & upgrade on regular basis, so I thought there might be an issue with updating the formula and decided to uninstall and untap it.

```
$ brew remove brew-rmtree
Uninstalling /usr/local/Cellar/brew-rmtree/2.0... (5 files, 20.4KB)

$ brew untap beeftornado/rmtree
Untapping beeftornado/rmtree... (36 files, 56.0KB)
Untapped 0 formulae

$ brew tap beeftornado/rmtree
==> Tapping beeftornado/rmtree
Cloning into '/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree'...
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 8 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
Tapped 0 formulae (36 files, 55.9KB)
```

As you can see Homebrew is unable to find any formulae in this repository.

I'm using Homebrew 1.6.0-15-g5005999.

**Comment by beginor** [comment]
I got this error too

```sh
$ brew rmtree wget
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/usr/local/bin/brew-rmtree.rb:45:in `<module:BrewRmtree>'
Or, even better, submit a PR to fix it!
```

brew version is:
```sh
$ brew --version
Homebrew 1.6.1
Homebrew/homebrew-core (git revision 875d5; last commit 2018-04-16)
```

**Comment by echosa** [comment]
I tried the same thing as @mikchmie-ifm with the same result. `brew` itself is update. (I run `brew update` almost daily, usually.) I removed `brew-rmtree`, untapped then re-tapped `beeftornado/rmtree`. No forumlae were tapped, and `brew install brew-rmtree` results in `No available formula with the name "brew-rmtree"`.

**Comment by beeftornado** [comment]
@mikchmie-ifm @echosa This tap doesn't contain any formulae since it is an [external command](https://github.com/Homebrew/brew/blob/master/docs/External-Commands.md). You only need to tap the repo to install the command.

I need a current stack trace before I can investigate this further. The one from the original author is dated and the problem should have been addressed in the previous update.

**Comment by beeftornado** [comment]
Also
```
Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
```
was removed over a year ago. You might need to untap and retap. I'm guessing homebrew may be preferring the old formula over the newer external command.

**Comment by beginor** [comment]
Untap rmtree first, and then remove rmtree, and update brew, then tap rmtree again, it works again!

```sh
brew untap beeftornado/homebrew-rmtree
brew remove beeftornado/homebrew-rmtree
brew update
brew tap beeftornado/homebrew-rmtree
```

Here is the result:

```sh
$ brew rmtree --help
brew rmtree [--force] [--dry-run] [--quiet] formula1 [formula2] [formula3]... [--ignore formulaX]

    Remove a formula entirely, including all of its dependencies,
    unless of course, they are used by another formula.
```

I think this issue can be closed!

**Comment by beeftornado** [comment]
@beginor Awesome, thanks! I just added a caveat upon updating that will prompt users to uninstall the formula if they had it. This is the path homebrew-cask followed when they made the switch.
