### ISSUE TITLE
Blocks on optional and build dependencies

### ISSUE THREAD

**Issue by sbibauw** [beeftornado/homebrew-rmtree#31]
When I run `brew rmtree formulaX`, it seems to systematically halt if other formulae have `formulaX` as an **optional** or **build** dependency, which should not, IMHO, be the default behaviour. 

e.g.

    $ brew rmtree python@2
    python@2 can't be removed because other formula depend on it:
    enchant, node
    
while 

     $ brew uses --installed python@2
     $ (nothing)

because `python@2` is an optional dep for `enchant` and a build dep for `node`.

I am not sure if there is an easy way to tell `rmtree` to ignore optional and build dependencies but NOT `required` dependencies (thus, not `--force`).

**Comment by beeftornado** [comment]
Tweaking the types of dependencies that get considered is trivial, but let's talk about that. It's good you brought this up. I think in this area it probably is a little *too* cautious.

I agree with excluding build dependencies, but I'm not so sure about optional ones. TBH I don't know much about homebrew (quite ironic), so I don't know what qualifies something as an optional dependency. Specifically, if that dependency were removed, would the dependent package lose functionality? Using your example, if we removed python2, would `enchant` work incorrectly? I really want `rmtree` to be as safe as possible just in case it goes off the rails.

I'm not very familiar with the ecosystem, so I don't know what types of things formulae list as optional. Are they truly "optional" or "optional, but yeah you kinda need it"?

If I go with what I know, I can offer an alternate solution, and filter out the build deps, and add a flag to turn on if someone really wants to skip the optional formula check too.

**Comment by sbibauw** [comment]
Good questions! My understanding of homebrew is limited too. Actually, besides `build` and `required` dependencies, there are 2 other kinds:
- `recommended`: included by default, but you can build a custom install without it
- `optional`: not included by default, but you can build a custom install with it
A good example for these 2 types of dependencies is `ffmpeg`: `lame` and `x264` are recommended (support for these codecs is included by default), while `libvorbis` and `x265` are optional, meaning that you can, if you want, build your own version with `brew install ffmpeg --with-x265 --without-x264`. So, rather than being `optional` or `recommended`, **what matters is whether the deps was actually included at install or not** (as it influences the build). If I (force) uninstall an installed optional/recommended dep afterwards, it might cause an error when trying to run the program (e.g., if I try to run `ffmpeg` after uninstalling `libvorbis`, even not needing this codec for a porcess, I get a `dyld: Library not loaded: /usr/local/opt/libvorbis/lib/libvorbisenc.2.dylib` error).

The good this is `brew uses --installed depname` knows whether or not an optional/recommended dependency was "activated" at install (it returns `ffmpeg` for `libvorbis`, and nothing for other optional deps that I didn't activate). `brew deps ffmpeg` on the contrary lists required and recommended deps (and optional with option `--include-optional`) independently from their actual use/activation at install. So you should probably try to gather deps the same way as `brew uses --installed`?
