### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by Loyalsoldier** [beeftornado/homebrew-rmtree#41]
`Error: Invalid usage: this command requires a keg argument`

![image](https://user-images.githubusercontent.com/10487845/89087231-2b337780-d3c6-11ea-89d0-dd2a790bc9f8.png)

**Comment by singularitti** [comment]
This happens to me, too.

**Comment by max-ae** [comment]
This issue likely occurs because of Homebrew/brew#8144
Maybe someone can look into it.
