### ISSUE TITLE
Problem with multiple homebrew installations

### ISSUE THREAD

**Issue by prinsss** [beeftornado/homebrew-rmtree#46]
I followed [this guide](https://noahpeeters.de/posts/apple-silicon/homebrew-setup/) to install both ARM and x86 version of homebrew side-by-side, and tried to run command `ibrew rmtree autojump`, which actually stands for `arch --x86_64 /usr/local/bin/brew rmtree autojump`. 

I intended to remove the x86 version of autojump (installed to `/usr/local/bin/autojump`), however the ARM version (installed to `/opt/homebrew/bin/autojump`) was removed.

```
❯ ibrew rmtree autojump

==> Cleaning up packages safe to remove

Uninstalling /opt/homebrew/Cellar/autojump/22.5.3_2... (20 files, 169.8KB)
Uninstalling /opt/homebrew/Cellar/python@3.9/3.9.1_1... (3,897 files, 64.7MB)
Uninstalling /opt/homebrew/Cellar/gdbm/1.18.1_1... (25 files, 876.2KB)
Uninstalling /opt/homebrew/Cellar/sqlite/3.34.0... (11 files, 4.2MB)
Uninstalling /opt/homebrew/Cellar/readline/8.1... (48 files, 1.7MB)
Uninstalling /opt/homebrew/Cellar/xz/5.2.5... (95 files, 1.4MB)
```

How can I specify which homebrew installation to use?

**Comment by beeftornado** [comment]
Good find. Since we've hardcoded the usage of `brew`, it's impossible for users to specify which installation formulae should be removed from. 

I can try using `HOMEBREW_PREFIX` ([ref](https://docs.brew.sh/External-Commands#other-executable-scripts)) to discern which `brew` to use.

**Comment by beeftornado** [comment]
@prinsss Let me know if this is fixed for you. I took a shot at it in https://github.com/beeftornado/homebrew-rmtree/commit/e755439c5cf529ba1dfb93bfd2d2440ed0adbe91

**Comment by prinsss** [comment]
I can confirm that the bug was fixed with the latest commit and `ibrew rmtree` now uninstalls packages from the proper location (`/usr/local/Cellar`). Thank you!
