### ISSUE TITLE
Error: undefined method `uses_args' for Homebrew:Module

### ISSUE THREAD

**Issue by chadluo** [beeftornado/homebrew-rmtree#60]
Hi,

I'm trying to uninstall some packages but got the following error:

```
brew rmtree prettier
Error: undefined method `uses_args' for Homebrew:Module
/opt/homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:191:in `block (2 levels) in uses'
/opt/homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:148:in `all?'
/opt/homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:148:in `block in uses'
/opt/homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:147:in `select'
/opt/homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:147:in `uses'
/opt/homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:448:in `rmtree'
/opt/homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:565:in `block in main'
/opt/homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:565:in `each'
/opt/homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:565:in `main'
/opt/homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:569:in `<top (required)>'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:10:in `require'
/opt/homebrew/Library/Homebrew/extend/kernel.rb:10:in `require?'
/opt/homebrew/Library/Homebrew/brew.rb:94:in `<main>'
If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/beeftornado/homebrew-rmtree/issues/new
```

I think I got the latest rmtree package and the brew version is `4.2.17`

Can you have a look?

**Comment by konnano** [comment]
Seems to be unmaintained
Please use this if you like

https://github.com/konnano/brew_list

**Comment by caseyduquettesc** [comment]
Pull requests are welcome

**Comment by jeevic** [comment]
i have the same problem   
my brew version Homebrew 4.2.18

**Comment by boris1993** [comment]
Seems caused by [this commit in brew](https://github.com/Homebrew/brew/commit/fdc95d02c89655cdb9d5a5d6b153f953cfdd6499#diff-2c22a8e4df519ede038d14ceab4b608b37dd474043557c7eea9b79dc0c7a4f9cL18), which removed the definition of `self.uses_args`.
I'm trying to understand Ruby and see if I can fix it.

**Comment by boris1993** [comment]
Replacing `Homebrew.uses_args.parse` to `Homebrew::CLI::Parser.new.parse` leads to another error
```
Error: undefined method `args_includes_ignores' for Homebrew:Module
/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/cmd/brew-rmtree.rb:191:in `block (2 levels) in uses'
```
and I have no idea what should I do next.

Asked for help in https://github.com/orgs/Homebrew/discussions/5341 and see if anyone can kindly guide me.

**Comment by caseyduquettesc** [comment]
Thanks for that information. Let me see if I can get any further

**Comment by caseyduquettesc** [comment]
Looks like several things were moved/renamed/removed that rmtree used

**Comment by caseyduquettesc** [comment]
I think this needs to be refactored. I'll have to continue to look tonight

**Comment by caseyduquettesc** [comment]
Got it mostly working. Testing a few more things
